export enum EQueryKeys {
  GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES",
}

export enum EMutationKeys {
  CREATE_CATEGORY = "CREATE_CATEGORY",
  UPDATE_CATEGORY = "UPDATE_CATEGORY",
  DELETE_CATEGORY = "DELETE_CATEGORY",
}
