export enum EQueryKeys {
  GET_BOOKING_BY_ID = "GET_BOOKING_BY_ID",
  GET_ALL_BOOKINGS = "GET_ALL_BOOKINGS",
}

export enum EMutationKeys {
  CREATE_BOOKING = "CREATE_BOOKING",
  UPDATE_BOOKING = "UPDATE_BOOKING",
  DELETE_BOOKING = "DELETE_BOOKING",
}
