export enum EQueryKeys {
  GET_ALL_ROOMS = "GET_ALL_ROOMS",
  CHECK_UNIQUE_ROOM_NUMBER = "CHECK_UNIQUE_ROOM_NUMBER",
}

export enum EMutationKeys {
  CREATE_ROOM = "CREATE_ROOM",
  UPDATE_ROOM = "UPDATE_ROOM",
  DELETE_ROOM = "DELETE_ROOM",
  UNHIDE_ROOM = "UNHIDE_ROOM",
}
