import { nanoid } from "nanoid"
import { FormConfig } from "../types/types"
import { calcAge } from "../utils/calcAge"

export const DOG_CONFIG: FormConfig = {
  categories: {
    commonInfo: {
      title: "Общая информация",
      expandedFields: 6,
      fields: [
        {
          name: "name",
          id: nanoid(),
          type: "text",
          label: "Кличка",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          minLetters: 2,
          width: "full",
        },
        {
          name: "breed",
          id: nanoid(),
          type: "text",
          label: "Порода",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          minLetters: 2,
          width: "full",
        },
        {
          name: "birthDate",
          id: nanoid(),
          type: "date",
          isPast: true,
          label: "Дата рождения",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          width: "1/3",
        },
        {
          name: "age",
          id: nanoid(),
          type: "text",
          label: "Возраст",
          required: false,
          validationErr: "Укажите дату рождения",
          width: "1/3",
          valueFn: (data: { [key: string]: string }) => calcAge(data.birthDate),
          disabledFn: () => true,
        },
        {
          name: "sex",
          id: nanoid(),
          type: "select",
          options: [
            { value: "MALE", label: "М" },
            { value: "FEМALE", label: "Ж" },
          ],
          label: "Пол",
          required: true,
          width: "1/3",
        },
        {
          name: "isExhibition",
          id: nanoid(),
          type: "checkbox",
          label: "Выставочная собака",
          required: false,
        },
        {
          name: "color",
          id: nanoid(),
          type: "text",
          label: "Окрас",
          required: false,
          width: "full",
        },
        {
          name: "sign",
          id: nanoid(),
          type: "text",
          label: "Чип, клеймо, особые приметы",
          required: false,
          width: "full",
        },
      ],
    },
    health: {
      title: "Здоровье",
      expandedFields: 3,
      fields: [
        {
          name: "vaccine",
          id: nanoid(),
          type: "text",
          label: "Даты последних прививок, названия вакцин",
          required: false,
          width: "full",
        },
        {
          name: "chronicDisease",
          id: nanoid(),
          type: "radio",
          label: "Есть ли хронические заболевания?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "chronicDiseaseType",
          id: nanoid(),
          type: "text",
          label: "Какие хронические заболевания?",
          required: false,
          width: "full",
          valueFn: (data: { [key: string]: string }, value: string) =>
            data.chronicDisease || data.chronicDisease === undefined
              ? value
              : "Хронических заболеваний нет",
        },
        {
          name: "vetVisitDate",
          id: nanoid(),
          type: "date",
          isPast: true,
          label: "Дата последнего посещения ветврача",
          required: false,
          width: "full",
        },
        {
          name: "vetVisitReason",
          id: nanoid(),
          type: "text",
          label: "Причина последнего посещения врача",
          required: false,
          width: "full",
        },
        {
          name: "parasites",
          id: nanoid(),
          type: "text",
          label: "Дата обработки от глистов/паразитов",
          required: false,
          width: "full",
        },
        {
          name: "fleaMite",
          id: nanoid(),
          type: "text",
          label: "Даты обработки от блох/клещей с указанием препарата",
          required: false,
          width: "full",
        },
        {
          name: "surgery",
          id: nanoid(),
          type: "text",
          label: "Перенесенные операции (кастрация)",
          required: false,
          width: "full",
        },
        {
          name: "pastDisease",
          id: nanoid(),
          type: "text",
          label: "Перенесенные заболевания",
          required: false,
          width: "full",
        },
        {
          name: "allergy",
          id: nanoid(),
          type: "radio",
          label: "Есть ли аллергия?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "allergyType",
          id: nanoid(),
          type: "text",
          label: "На что аллергия?",
          required: false,
          width: "full",
          valueFn: (data: { [key: string]: string }, value: string) =>
            data.allergy || data.allergy === undefined
              ? value
              : "Известных аллергий нет",
        },
        {
          name: "heatDate",
          id: nanoid(),
          type: "date",
          isPast: false,
          label: "Дата начала течки (для сук)",
          required: false,
          width: "full",
        },
        {
          name: "vetData",
          id: nanoid(),
          type: "text",
          label: "Контакты ветврача",
          required: false,
          width: "full",
        },
      ],
    },
    behavior: {
      title: "Поведение и уход",
      expandedFields: 5,
      fields: [
        {
          name: "stayAlone",
          id: nanoid(),
          type: "text",
          label: "Умеет ли оставаться один?",
          required: false,
          width: "full",
        },
        {
          name: "specialCare",
          id: nanoid(),
          type: "text",
          label: "Требуется ли спец уход, какой?",
          required: false,
          width: "full",
        },
        {
          name: "newPeople",
          id: nanoid(),
          type: "text",
          label: "Как относится к незнакомым людям?",
          required: false,
          width: "full",
        },
        {
          name: "isDogTraining",
          id: nanoid(),
          type: "radio",
          label: "Прошел ли курс послушания?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "trainingName",
          id: nanoid(),
          type: "text",
          label: "Какой курс послушания прошел?",
          required: false,
          width: "full",
          valueFn: (data: { [key: string]: string }, value: string) =>
            data.isDogTraining || data.isDogTraining === undefined
              ? value
              : "Курс послушания не проходил",
        },
        {
          name: "stayWithoutMaster",
          id: nanoid(),
          type: "text",
          label: "Есть ли опыт разлуки с хозяином?",
          required: false,
          width: "full",
        },
        {
          name: "barkHowl",
          id: nanoid(),
          type: "text",
          label: "Лает/воет в одиночестве?",
          required: false,
          width: "full",
        },
        {
          name: "furnitureDamage",
          id: nanoid(),
          type: "text",
          label: "Портит ли вещи, мебель?",
          required: false,
          width: "full",
        },
        {
          name: "foodFromTable",
          id: nanoid(),
          type: "text",
          label: "Ворует ли еду со стола?",
          required: false,
          width: "full",
        },
        {
          name: "defecateAtHome",
          id: nanoid(),
          type: "text",
          label: "Справляет ли нужду дома?",
          required: false,
          width: "full",
        },
        {
          name: "markAtHome",
          id: nanoid(),
          type: "text",
          label: "Метит дома?",
          required: false,
          width: "full",
        },
        {
          name: "isBitePeople",
          id: nanoid(),
          type: "radio",
          label: "Кусал ли кого-то когда-нибудь?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "reasonOfBite",
          id: nanoid(),
          type: "text",
          label: "Причина, почему кусал",
          required: false,
          width: "full",
          valueFn: (data: { [key: string]: string }, value: string) =>
            data.isBitePeople || data.isBitePeople === undefined
              ? value
              : "Людей не кусал",
        },
        {
          name: "playWithDogs",
          id: nanoid(),
          type: "text",
          label: "Играет/гуляет с другими собаками?",
          required: false,
          width: "full",
        },
        {
          name: "toys",
          id: nanoid(),
          type: "text",
          label: "Любимые игрушки, игры",
          required: false,
          width: "full",
        },
        {
          name: "walking",
          id: nanoid(),
          type: "text",
          label: "Сколько раз в день привык гулять?/Гуляет ли на улице?",
          required: false,
          width: "full",
        },
        {
          name: "morningWalking",
          id: nanoid(),
          type: "text",
          label: "Утро. Привычное время прогулок",
          required: false,
          width: "full",
        },
        {
          name: "dayWalking",
          id: nanoid(),
          type: "text",
          label: "День. Привычное время прогулок",
          required: false,
          width: "full",
        },
        {
          name: "eveningWalking",
          id: nanoid(),
          type: "text",
          label: "Вечер. Привычное время прогулок",
          required: false,
          width: "full",
        },
      ],
    },
    feeding: {
      title: "Питание",
      expandedFields: 1,
      fields: [
        {
          name: "feedType",
          id: nanoid(),
          type: "text",
          label: "Вид корма (сухой/натуралка/консервы)",
          required: false,
          width: "full",
        },
        {
          name: "feedingQuantity",
          id: nanoid(),
          type: "slider",
          label: "Количество кормлений в день",
        },
        {
          name: "feedName",
          id: nanoid(),
          type: "text",
          label: "Название корма/консервов",
          required: false,
          width: "full",
        },
        {
          name: "feedComposition",
          id: nanoid(),
          type: "text",
          label: "Состав корма/консервов",
          required: false,
          width: "full",
        },
        {
          name: "feedingRate",
          id: nanoid(),
          type: "text",
          label: "Норма на 1 кормление",
          required: false,
          width: "full",
        },
        {
          name: "feedingPractice",
          id: nanoid(),
          type: "text",
          label: "Особенности кормления",
          required: false,
          width: "full",
        },
        {
          name: "treat",
          id: nanoid(),
          type: "text",
          label: "Разрешенные лакомства и их количество",
          required: false,
          width: "full",
        },
        {
          name: "isMedicine",
          id: nanoid(),
          type: "radio",
          label: "Необходимы лекарства, витамины?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "medicineRegimen",
          id: nanoid(),
          type: "text",
          label: "Название, режим приема лекарств/витаминов и доза",
          required: false,
          width: "full",
          valueFn: (data: { [key: string]: string }, value: string) =>
            data.isMedicine || data.isMedicine === undefined
              ? value
              : "Лекарства/Витамины не нужны",
        },
      ],
    },
    comment: {
      title: "Дополнительная информация",
      expandedFields: 1,
      fields: [
        {
          name: "additionalInfo",
          id: nanoid(),
          type: "text",
          label: "Дополнительная информация",
          required: false,
          width: "full",
          isTextArea: true,
        },
      ],
    },
  },
}
