import { nanoid } from "nanoid"
import { FormConfig } from "./types"

export const EXOT_CONFIG: FormConfig = {
  categories: {
    commonInfo: {
      title: "Общая информация",
      expandedFields: 6,
      fields: [
        {
          name: "name",
          id: nanoid(),
          type: "text",
          label: "Кличка",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          minLetters: 2,
          width: "full",
        },
        {
          name: "breed",
          id: nanoid(),
          type: "text",
          label: "Порода/Вид",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          minLetters: 2,
          width: "full",
        },
        {
          name: "birthDate",
          id: nanoid(),
          type: "date",
          isPast: true,
          label: "Дата рождения",
          required: true,
          validationErr: "Пожалуйста, заполните это поле",
          width: "1/3",
        },
        {
          name: "age", //omit
          id: nanoid(),
          type: "text",
          label: "Возраст",
          required: false,
          width: "1/3",
        },
        {
          name: "sex",
          id: nanoid(),
          type: "select",
          options: [
            { value: "MALE", label: "М" },
            { value: "FEМALE", label: "Ж" },
            { value: "HERMAPHRODITE", label: "Другое" },
          ],
          label: "Пол",
          required: true,
          width: "1/3",
        },
        {
          name: "color",
          id: nanoid(),
          type: "text",
          label: "Окрас",
          required: false,
          width: "full",
        },
        {
          name: "sign",
          id: nanoid(),
          type: "text",
          label: "Чип, клеймо, особые приметы",
          required: false,
          width: "full",
        },
      ],
    },
    health: {
      title: "Здоровье",
      expandedFields: 3,
      fields: [
        {
          name: "vaccine",
          id: nanoid(),
          type: "text",
          label: "Даты последних прививок, названия вакцин",
          required: false,
          width: "full",
        },
        {
          name: "vetVisitDate",
          id: nanoid(),
          type: "date",
          isPast: true,
          label: "Дата последнего посещения ветврача",
          required: false,
          width: "full",
        },
        {
          name: "vetVisitReason",
          id: nanoid(),
          type: "text",
          label: "Причина последнего посещения врача",
          required: false,
          width: "full",
        },
        {
          name: "parasites",
          id: nanoid(),
          type: "text",
          label: "Дата обработки от глистов/паразитов",
          required: false,
          width: "full",
        },
        {
          name: "pastDisease",
          id: nanoid(),
          type: "text",
          label: "Перенесенные заболевания",
          required: false,
          width: "full",
        },
        {
          name: "vetData",
          id: nanoid(),
          type: "text",
          label: "Контакты ветврача",
          required: false,
          width: "full",
        },
      ],
    },
    behavior: {
      title: "Поведение и уход",
      expandedFields: 6,
      fields: [
        {
          name: "newPeople",
          id: nanoid(),
          type: "text",
          label: "Как относится к незнакомым людям?",
          required: false,
          width: "full",
        },
        {
          name: "stayWithoutMaster",
          id: nanoid(),
          type: "text",
          label: "Есть ли опыт разлуки с хозяином?",
          required: false,
          width: "full",
        },
        {
          name: "like",
          id: nanoid(),
          type: "text",
          label: "Что любит?",
          required: false,
          width: "full",
        },
        {
          name: "notLike",
          id: nanoid(),
          type: "text",
          label: "Что не любит?",
          required: false,
          width: "full",
        },
        {
          name: "toys",
          id: nanoid(),
          type: "text",
          label: "Любимые игрушки, игры",
          required: false,
          width: "full",
        },
        {
          name: "badHabit",
          id: nanoid(),
          type: "text",
          label: "Вредные привычки",
          required: false,
          width: "full",
        },
      ],
    },
    feeding: {
      title: "Питание",
      expandedFields: 1,
      fields: [
        {
          name: "feedType",
          id: nanoid(),
          type: "text",
          label: "Вид корма (сухой/натуралка/консервы)",
          required: false,
          width: "full",
        },
        {
          name: "feedName",
          id: nanoid(),
          type: "text",
          label: "Название корма/консервов",
          required: false,
          width: "full",
        },
        {
          name: "feedComposition",
          id: nanoid(),
          type: "text",
          label: "Состав корма/консервов",
          required: false,
          width: "full",
        },
        {
          name: "feedingRate",
          id: nanoid(),
          type: "text",
          label: "Норма на 1 кормление",
          required: false,
          width: "full",
        },
        {
          name: "feedingPractice",
          id: nanoid(),
          type: "text",
          label: "Особенности кормления",
          required: false,
          width: "full",
        },
        {
          name: "treat",
          id: nanoid(),
          type: "text",
          label: "Разрешенные лакомства и их количество",
          required: false,
          width: "full",
        },
        {
          name: "isMedicine",
          id: nanoid(),
          type: "radio",
          label: "Необходимы лекарства, витамины?",
          required: false,
          options: [
            { value: true, label: "Да" },
            { value: false, label: "Нет" },
          ],
        },
        {
          name: "medicineRegimen",
          id: nanoid(),
          type: "text",
          label: "Название, режим приема лекарств/витаминов и доза",
          required: false,
          width: "full",
        },
      ],
    },
  },
}
