export enum queryKeys {
  GET_ALL_CLIENTS = "GET_ALL_USERS",
  GET_SUGGESTED_CLIENTS = "GET_SUGGESTED_CLIENTS",
  GET_CLIENT_BY_ID = "GET_CLIENT_BY_ID",
}

export enum EMutationKeys {
  CREATE_CLIENTS = "CREATE_CLIENTS",
}
